#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
SUPABASE_PROJECT_REF="knhyixsjidjsfytgqnjn"
SUPABASE_SMTP_URL="https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/auth"

banner "Supabase SMTP setup — PortalContabil.cloud"

note "Why this exists: without your own SMTP server, Supabase sends auth"
note "e-mails (invite, password reset) through its own shared mailer, which"
note "caps you at a couple of e-mails per hour project-wide. That's the"
note "\"email rate limit exceeded\" / \"Muitas tentativas em pouco tempo\""
note "error you've been hitting. Custom SMTP removes that cap — you're then"
note "limited only by your own e-mail provider's plan."
note ""
note "This wizard captures your SMTP credentials locally (never sent"
note "anywhere by this script) so you have them all in one place to paste"
note "into the Supabase Dashboard — the actual save happens there, not here."

# ── Stage 1: pick a provider ───────────────────────────────────────────────
stage "Escolher um provedor de SMTP"
say "Qualquer um destes funciona com o Supabase. Free tiers aproximados:"
say ""
say "  ${BOLD}Resend${RESET}    — 3.000 e-mails/mês grátis, setup mais simples, boa fama de entregabilidade."
say "  ${BOLD}SendGrid${RESET}  — 100 e-mails/dia grátis, painel mais robusto."
say "  ${BOLD}Postmark${RESET}  — 100 e-mails/mês grátis no plano trial, focado em e-mails transacionais."
say "  ${BOLD}Amazon SES${RESET} — extremamente barato em volume, mas exige mais configuração (DNS/SPF/DKIM)."
say ""
say "Recomendação para começar: Resend (mais rápido de configurar)."
ask SMTP_PROVIDER "Qual você vai usar? (resend/sendgrid/postmark/ses/outro):"

case "${SMTP_PROVIDER,,}" in
  resend)
    open_url "https://resend.com/signup"
    step "Crie a conta, depois vá em Domains → adicione seu domínio (ou use o domínio de testes deles para validar rápido)."
    step "Vá em API Keys → Create API Key. O SMTP host do Resend é smtp.resend.com, porta 465 (SSL) ou 587 (TLS)."
    note "No Resend, o usuário SMTP é literalmente a palavra 'resend' e a senha é a API key gerada."
    ;;
  sendgrid)
    open_url "https://signup.sendgrid.com/"
    step "Crie a conta, depois vá em Settings → Sender Authentication para verificar seu domínio."
    step "Vá em Settings → API Keys → Create API Key (permissão 'Mail Send' basta)."
    note "No SendGrid, o usuário SMTP é literalmente 'apikey' e a senha é a API key gerada. Host: smtp.sendgrid.net, porta 587."
    ;;
  postmark)
    open_url "https://account.postmarkapp.com/sign_up"
    step "Crie a conta, depois crie um 'Server' e um 'Sender Signature' (ou domínio verificado)."
    step "Nas configurações do Server, copie o SMTP Token — ele serve tanto de usuário quanto de senha."
    note "Host do Postmark: smtp.postmarkapp.com, porta 587."
    ;;
  ses|aws|amazon\ ses)
    open_url "https://console.aws.amazon.com/ses/"
    step "Verifique seu domínio (SES → Verified identities) e configure os registros DNS pedidos."
    step "Vá em SES → SMTP Settings → Create SMTP credentials para gerar usuário/senha específicos de SMTP."
    note "Host varia por região, ex.: email-smtp.us-east-1.amazonaws.com, porta 587."
    ;;
  *)
    warn "Provedor não reconhecido — sem problema, qualquer SMTP padrão funciona."
    say "Você vai precisar do host, porta, usuário e senha SMTP desse provedor."
    ;;
esac
pause "Quando tiver a conta criada e as credenciais SMTP em mãos, Enter para continuar."

# ── Stage 2: capture credentials ────────────────────────────────────────────
stage "Anotar as credenciais SMTP"
say "Vamos guardar isso aqui só para você colar na tela do Supabase no próximo"
say "passo — este script NÃO envia essas credenciais para lugar nenhum."
ask SMTP_HOST "Host SMTP (ex.: smtp.resend.com):"
ask SMTP_PORT "Porta (587 é o mais comum):"
ask SMTP_USER "Usuário SMTP:"
ask_secret SMTP_PASSWORD "Senha / API key SMTP:"

# ── Stage 3: sender identity ────────────────────────────────────────────────
stage "Definir o remetente (nome + e-mail)"
say "É isso que o cliente vê na caixa de entrada — deve ser a marca"
say "PortalContabil.cloud, nunca Supabase."
note "O e-mail do remetente precisa ser de um domínio verificado no provedor"
note "escolhido no Stage 1 (ex.: nao-responda@portalcontabil.cloud)."
ask SMTP_SENDER_NAME "Nome do remetente (ex.: PortalContabil.cloud):"
ask SMTP_SENDER_EMAIL "E-mail do remetente (ex.: nao-responda@portalcontabil.cloud):"

# ── Stage 4: configure in Supabase Dashboard ────────────────────────────────
stage "Configurar no Supabase Dashboard"
say "Projeto: Ia-cloude (ref ${SUPABASE_PROJECT_REF})"
open_url "$SUPABASE_SMTP_URL"
step "Na página que abriu, procure a seção 'SMTP Settings' e ative 'Enable Custom SMTP'."
step "Preencha os campos com os valores abaixo (copie e cole):"
say ""
say "    Sender email:  ${BOLD}${SMTP_SENDER_EMAIL}${RESET}"
say "    Sender name:   ${BOLD}${SMTP_SENDER_NAME}${RESET}"
say "    Host:          ${BOLD}${SMTP_HOST}${RESET}"
say "    Port:          ${BOLD}${SMTP_PORT}${RESET}"
say "    Username:      ${BOLD}${SMTP_USER}${RESET}"
say "    Password:      ${DIM}(a que você digitou no Stage 2 — oculta aqui de propósito)${RESET}"
say ""
step "Clique em Save."
pause "Salvou? Enter para continuar."

# ── Stage 5: send a test email ──────────────────────────────────────────────
stage "Enviar um e-mail de teste"
say "Ainda na mesma página do Supabase, procure a opção de enviar um e-mail"
say "de teste (nem todo projeto mostra esse botão — se não tiver, pule para"
say "o próximo estágio e teste direto pelo fluxo real do app)."
ask TEST_EMAIL_ADDRESS "Endereço para receber o teste (pode ser o seu):"
step "Envie o teste para ${TEST_EMAIL_ADDRESS} e confira a caixa de entrada (e o spam)."
confirm "Chegou o e-mail de teste?" && say "Ótimo — SMTP customizado está funcionando." \
  || warn "Sem e-mail? Revise host/porta/usuário/senha no Stage 4 antes de seguir."

# ── Stage 6: confirm the rate limit is gone ─────────────────────────────────
stage "Confirmar que o limite de envio sumiu"
say "Agora teste pelo fluxo real do PortalContabil.cloud:"
step "Abra o app (npm run dev) → tela de login → 'Esqueci minha senha'."
step "Peça a redefinição de senha 3 vezes seguidas para o mesmo e-mail."
note "Com o Supabase SMTP padrão isso travava na segunda/terceira tentativa"
note "com \"Muitas tentativas em pouco tempo\". Com SMTP próprio, cada"
note "tentativa deve mandar um e-mail normalmente (respeitando o limite do"
note "seu provedor, que é bem mais alto)."
confirm "Funcionou sem o erro de rate limit?" \
  && note "SMTP customizado configurado com sucesso." \
  || SKIPPED+=("Revisar configuração SMTP no Supabase Dashboard — rate limit ainda apareceu")

finish
note "Nenhuma credencial deste wizard foi salva em arquivo — elas só existiram"
note "na sessão do terminal e já foram descartadas ao configurar no Supabase."
