#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Este wizard escreve em backend/.env (nao em .env na raiz) — e onde o
# FastAPI (pydantic-settings, backend/app/core/config.py) le SMTP_HOST/
# SMTP_PORT/SMTP_USER/SMTP_PASSWORD/SMTP_FROM. Precisa ser rodado a partir
# da raiz do repo.
ENV_FILE="backend/.env"

TOTAL_STAGES=3

banner "SMTP para envio de relatórios por e-mail"

# ── Stage 1: escolher provedor ─────────────────────────────────────────────
stage "Escolher provedor de e-mail"
say "O PortalContabil.cloud usa isso só para o botão \"Enviar por e-mail\" dos"
say "relatórios (anexo em PDF/XLS/CSV) — é separado do e-mail de login/senha"
say "do Supabase, que já está configurado à parte."
say ""
say "Três opções:"
say "  1) Resend — 100 e-mails/dia grátis, o mais simples de configurar."
say "  2) Gmail com Senha de App — grátis, bom para pouco volume, exige"
say "     verificação em duas etapas ativada na conta Google."
say "  3) SMTP do seu próprio domínio — se você já tem e-mail corporativo"
say "     (ex: via cPanel/Hostinger/Zoho) e sabe o host/porta SMTP dele."
say ""
ask PROVEDOR_SMTP "Digite 1, 2 ou 3:"

case "$PROVEDOR_SMTP" in
  1)
    say ""
    say "Resend selecionado."
    open_url "https://resend.com/signup"
    step "Crie uma conta grátis (ou faça login se já tiver uma)."
    pause "Conta criada/logada?"
    open_url "https://resend.com/api-keys"
    step "Clique em \"Create API Key\", dê um nome (ex: portalcontabil-relatorios)."
    step "Copie a chave gerada (começa com re_) — só aparece uma vez."
    note "O Resend usa SMTP com usuário fixo 'resend' e a API key como senha."
    ask_secret RESEND_API_KEY "Cole a API key do Resend:"
    SMTP_HOST="smtp.resend.com"
    SMTP_PORT="587"
    SMTP_USER="resend"
    SMTP_PASSWORD="$RESEND_API_KEY"
    note "Lembrete: se o remetente (próximo estágio) usar um domínio próprio"
    note "(não @resend.dev), você precisa verificá-lo em resend.com/domains"
    note "antes dos e-mails saírem — senão o Resend rejeita o envio."
    ;;
  2)
    say ""
    say "Gmail com Senha de App selecionado."
    open_url "https://myaccount.google.com/security"
    step "Confirme que \"Verificação em duas etapas\" está ATIVADA (obrigatório"
    step "para gerar Senha de App — se não estiver, ative antes de continuar)."
    pause "Verificação em duas etapas confirmada?"
    open_url "https://myaccount.google.com/apppasswords"
    step "Em \"Nome do app\", digite algo como \"PortalContabil relatorios\"."
    step "Clique em Criar e copie a senha de 16 letras gerada."
    ask GMAIL_ENDERECO "Digite o endereço Gmail usado (ex: seuemail@gmail.com):"
    ask_secret GMAIL_APP_PASSWORD "Cole a senha de app (16 letras, sem espaços):"
    SMTP_HOST="smtp.gmail.com"
    SMTP_PORT="587"
    SMTP_USER="$GMAIL_ENDERECO"
    SMTP_PASSWORD="$GMAIL_APP_PASSWORD"
    ;;
  *)
    say ""
    say "SMTP do próprio domínio selecionado."
    note "Pegue esses dados no painel do seu provedor de hospedagem/e-mail"
    note "(cPanel → E-mail Accounts → Connect Devices, ou equivalente)."
    ask SMTP_HOST "Host SMTP (ex: mail.portalcontabil.cloud):"
    ask SMTP_PORT "Porta SMTP (geralmente 587):"
    ask SMTP_USER "Usuário/e-mail completo:"
    ask_secret SMTP_PASSWORD "Senha:"
    ;;
esac
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 2: remetente ──────────────────────────────────────────────────────
stage "Endereço de remetente"
say "Esse é o \"De:\" que aparece pro destinatário do relatório."
ask SMTP_FROM "Remetente [Enter usa \"PortalContabil.cloud <nao-responda@portalcontabil.cloud>\"]:"
if [[ -z "$SMTP_FROM" ]]; then
  SMTP_FROM="PortalContabil.cloud <nao-responda@portalcontabil.cloud>"
fi
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 3: gravar no .env ─────────────────────────────────────────────────
stage "Gravar em backend/.env"
write_env SMTP_HOST "$SMTP_HOST"
write_env SMTP_PORT "$SMTP_PORT"
write_env SMTP_USER "$SMTP_USER"
write_env SMTP_PASSWORD "$SMTP_PASSWORD"
write_env SMTP_FROM "$SMTP_FROM"
warn "O backend local precisa ser reiniciado para carregar essas variáveis novas."
note "(pydantic-settings só lê o .env na inicialização do processo)"
# ──────────────────────────────────────────────────────────────────────────

finish
